### ISSUE TITLE
Problem of Reverse

### ISSUE THREAD

**Issue by pxxiao-hz** [BGI-shenzhen/RectChr#2]
Hello,

When I reversed the chromosomes, I get the following result. Is this a bug? Or I did in a wrong way.

![OUT](https://user-images.githubusercontent.com/76642822/198883610-8ea1e87b-c44f-4b01-8263-ddc644c65faa.svg)

**Comment by hewm2008** [comment]
I  don't know the content of your  xx.cofi .
my n ew software **NGenomeSyn** is recommended.    visualization of syntenic relationships on any number of genomes 
see  this 
https://github.com/hewm2008/NGenomeSyn

**Comment by pxxiao-hz** [comment]
Thanks for your reply, I will use NGenomeSyn.

**Comment by hewm2008** [comment]
if  you have a QQ number, 
you can join in the QQ Group : 125293663  to Contact  me

**Comment by pxxiao-hz** [comment]
ok.
